# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr: 
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main 
  tags:
    include:
      - "*"
  
variables:
  - name: dockerRepository
    value: "dbinclui/backend"
   
  - name: acrServiceConnection
    value: "docker-registry"

  - name: buildId
    value: $(Build.BuildId)
  
  - name: isTag
    value: ${{startsWith(variables['Build.SourceBranch'],'refs/tags/')}}

  - name: isMergePR
    value: ${{ne(variables['Build.Reason'], 'PullRequest')}}
  
  - name: branchName
    value: $(Build.SourceBranchName)

  

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    variables:
      - group: dbinclui-api-envs-dev
    jobs:
      - job: CI
        displayName: Run tests, build and push image to ACR
        steps:      
          - task: Npm@1
            displayName: "install dependencies"
            inputs:
              command: "install"

          - task: Npm@1
            displayName: "Build"
         #   condition: or(eq(variables['isTag'], 'true'), eq(variables['isMergePR'], 'true'))
            inputs:
              command: custom
              customCommand: "run build"
          
          - task: Docker@2
            displayName: "build and publish container docker registry"
            condition: and(succeeded(), or(eq(variables['isMergePR'], 'true'), eq(variables['isTag'], 'true')))
            inputs:
              containerRegistry: 'docker-registry'
              repository: 'dbinclui/backend'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              arguments: '--build-arg NODE_ENV=${NODE_ENV_DBINCLUI} --build-arg HOST=${HOST_DBINCLUI} --build-arg PORT=${PORT_DBINCLUI} --build-arg MONGO_URL=${MONGO_URL_DBINCLUI} --build-arg MONGO_DATABASE=${MONGO_DATABASE_DBINCLUI} --build-arg FIREBASE_TYPE=${FIREBASE_TYPE_DBINCLUI} --build-arg FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID_DBINCLUI} --build-arg FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID_DBINCLUI} --build-arg FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY_DBINCLUI} --build-arg  FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL_DBINCLUI}  --build-arg FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID_DBINCLUI} --build-arg FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI_DBINCLUI} --build-arg FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI_DBINCLUI} --build-arg FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL_DBINCLUI} --build-arg FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL_DBINCLUI}'
             # ${{ if eq(variables['isTag'], 'true') }}:
              #  tags: $(branchName)
             # ${{ else }}:
              #  tags: |
               #   $(buildId)
                #  latest  
                
  - stage: DeployToDevelopment
    dependsOn: CI
    condition: and(succeeded(), eq(variables['isMergePR'], 'true'), ne(variables['isTag'], 'true'))
    variables:
      - group: dbinclui-api-envs-dev
      - name: enviroment
        value: "dev"

    jobs:
      - job: ApplyManifests
        displayName: Applying kubernetes manifests
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: env
          - task: ShellScript@2
            displayName: Changing yaml's variables
            inputs:
              scriptPath: "./kubernetes/change_variables.sh"
          - task: Kubernetes@1
            displayName: Create ConfigMap
            inputs:
              connectionType: $(connectionType)
              kubernetesServiceEndpoint: $(aksServiceConnection)
              namespace: $(k8sNamespace)
              containerRegistryType: "Azure Container Registry"
              configMapName: "dbinclui-api-configmap-dev"
              forceUpdateConfigMap: true
              configMapArguments: >
                --from-literal=MONGO_URL=${MONGO_URL_DBINCLUI}
                --from-literal=MONGO_DATABASE=${MONGO_DATABASE_DBINCLUI}
                --from-literal=FIREBASE_TYPE=${FIREBASE_TYPE_DBINCLUI}
                --from-literal=FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID_DBINCLUI}
                --from-literal=FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID_DBINCLUI}
                --from-literal=FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY_DBINCLUI}
                --from-literal=FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL_DBINCLUI}
                --from-literal=FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID_DBINCLUI}
                --from-literal=FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI_DBINCLUI}
                --from-literal=FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI_DBINCLUI}
                --from-literal=FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL_DBINCLUI}
                --from-literal=FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL_DBINCLUI}
                --from-literal=CLOUD_NAME=${CLOUD_NAME_DBINCLUI}
                --from-literal=CLOUD_API_KEY=${CLOUD_API_KEY_DBINCLUI}
                --from-literal=CLOUD_API_SECRET=${CLOUD_API_SECRE_DBINCLUI}

                  - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes
                  inputs:
                    action: deploy
                    namespace: $(k8sNamespace)
                    kubernetesServiceConnection: $(aksServiceConnection)
                    manifests: |
                      ./kubernetes/deployment.yaml
                      ./kubernetes/service.yaml
                    containers: |
                      $(acrUrl):latest
                - task: Kubernetes@1
                  displayName: Restart service
                  inputs:
                    connectionType: $(connectionType)
                    kubernetesServiceEndpoint: $(aksServiceConnection)
                    namespace: $(k8sNamespace)
                    command: "rollout"
                    arguments: "restart deploy dbinclui-api-dev"
