apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbinclui-api-${env}
  namespace: dbinclui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbinclui-api-${env}
  template:
    metadata:
      labels:
        app: dbinclui-api-${env}
    spec:
      containers:
        - name: dbinclui-api-${env}
          image: "dbserverregistry.azurecr.io/dbinclui/backend"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: dbinclui-api-configmap-${env}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/readiness
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
