apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: dbinclui-api
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    spec:
      rules:
        - host: dbinclui-api.paas.dbserver.com.br
          http:
            paths:
              - pathType: Prefix
                path: /
                backend:
                  service:
                    name: dbinclui-api-service
                    port:
                      number: 80
      tls:
        - hosts:
            - dbinclui-api.paas.dbserver.com.br
          secretName: dbinclui-api
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
