apiVersion: v1
kind: Service
metadata:
  name: dbinclui-api-service-${env}
  namespace: dbinclui
  labels:
    app: dbinclui-api-${env}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: dbinclui-api-${env}
